version: "3.8"

services:
  backend:
    build:
      context: ./Backend
      dockerfile: Dockerfile
    command: gunicorn server.wsgi:application --bind 0.0.0.0:8000
    volumes:
      - ./backend:/app
    env_file:
      - ./Backend/.env
    ports:
      - 8000:8000
    networks:
      - app-network

  frontend:
    build:
      context: ./Frontend/henon-dashboard
      dockerfile: Dockerfile
      args:
        VITE_BACKEND_URL: http://localhost:8000
    ports:
      - 80:80
    env_file:
      - ./Frontend/henon-dashboard/.env
    depends_on:
      - backend
    networks:
      - app-network

  prometheus:
    image: prom/prometheus:latest
    container_name: prometheus
    volumes:
      - ./prometheus.yml:/etc/prometheus/prometheus.yml
    ports:
      - "9090:9090"

  grafana:
    image: grafana/grafana:latest
    container_name: grafana
    ports:
      - "3000:3000"
    environment:
      - GF_SECURITY_ADMIN_PASSWORD=admin
    depends_on:
      - prometheus
    volumes:
      - grafana_data:/var/lib/grafana

networks:
  app-network:

volumes:
  grafana_data:
